# ParsersConfig config
sv-company:
  active: false
  url: https://sv-company.ru/
  class: App\Parser\Spider\Spider
  items_list_url: https://sv-company.ru/avtozapchasti/avtozapchasti-b-u/
  url_pattern: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/.+/
  url_pattern_detail: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/[^\/]+\/$/
  items_list_selector: .//a
  selectors:
      title: .//h1[@class="product__title"]
      brand: .//nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[3]/a
      model: .//nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[4]/a
      img: .//img[@class="gallery__img"][1]/@src
      price: .//span[@class="product__price"]
      isAvalable: .//tbody/tr[td='Статус']/td[2]

razbor-nt:
  active: true
  url: http://razbor-nt.ru/
  class: App\Parser\Spider\Spider
  items_list_url: http://razbor-nt.ru/
  items_list_selector: .//a
  url_pattern: /http:\/\/razbor-nt.ru\/[^\/]+\//
  url_pattern_detail: /http:\/\/razbor-nt.ru\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+.html$/
  request_dalay: 500
  selectors:
      title: //*[@id="content"]/div[@class="b1c-good"]/h1
      brand: //*[@id="content"]/div/div[@class="breadcrumb-style"]/a[2]
      model: //*[@id="content"]/div/div[@class="breadcrumb-style"]/a[3]
      img: //*[@id="image"]/@src
      price: //div[@class="price"]

разборкасокол:
  active: false
  url: https://разборкасокол.рф/
  class: App\Parser\Spider\Spider
  items_list_url: https://разборкасокол.рф/
  items_list_selector: .//a
  url_pattern: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/.+/
  url_pattern_detail: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/[^\/]+\/[^\/]+.html$/
  max_depth: 7
  selectors:
      title: //*[@id="content"]/h1
      brand: //div[@class="breadcrumb"]/a[2]
      description: //div[@class="opisanie_tovar"]
      img: //*[@id="image"]/@src
      price: //div[@class="price"][1]

autoinfo51:
  active: false
  url: http://www.autoinfo51.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://www.autoinfo51.ru
  items_list_selector: .//a
  url_pattern: /^http:\/\/www.autoinfo51.ru\/catalog\/.+/
  url_pattern_detail: /^http:\/\/www.autoinfo51.ru\/catalog\/[\d]+\/[\d]+\/$/
  max_depth: 4
  request_dalay: 500
  selectors:
      row: //table[@class="catalog"]/tr[position() >= 2]
      model: //td[2]
      title: //td[3]
      description: //td[5]
      price: //td[6]
      img: //td[7]/a/@href