# ParsersConfig config
sv-company:
  active: true
  url: https://sv-company.ru/
  class: App\Parser\Spider\DefaultSpider
  work_time:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '12:00'}
      - {time_from: '12:00', time_to: '22:00'}
    Wednesdays:
      - {time_from: '10:00', time_to: '18:20'}
    Thursdays:
      - {time_from: '10:00', time_to: '12:40'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}

  items_list_url: https://sv-company.ru/avtozapchasti/avtozapchasti-b-u/
  url_pattern: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/.+/
  url_pattern_detail: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/[^\/]+\/$/
  items_list_selector: .//a
  selectors:
      title: .//h1[@class="product__title"]
      img: .//img[@class="gallery__img"][1]/@src
      price: .//span[@class="product__price"]
      isAvalable: .//tbody/tr[td='Статус']/td[2]

razbor-nt:
  active: true
  url: http://razbor-nt.ru/
  class: App\Parser\Spider\DefaultSpider
  work_time:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '12:00'}
      - {time_from: '12:00', time_to: '22:00'}
    Wednesdays:
      - {time_from: '10:00', time_to: '20:00'}
    Thursdays:
      - {time_from: '12:38', time_to: '12:45'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}
  items_list_url: http://razbor-nt.ru/
  items_list_selector: .//a
  url_pattern: /http:\/\/razbor-nt.ru\/[^\/]+\//
  url_pattern_detail: /http:\/\/razbor-nt.ru\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+.html$/
  request_dalay: 500
  selectors:
      title: //*[@id="content"]/div[@class="b1c-good"]/h1
      url: //*[@id="image"]/@src
      price: //div[@class="price"]

разборкасокол:
  active: true
  url: https://разборкасокол.рф/
  class: App\Parser\Spider\DefaultSpider
  work_time:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '12:00'}
      - {time_from: '12:00', time_to: '22:00'}
    Wednesdays:
      - {time_from: '10:00', time_to: '20:00'}
    Thursdays:
      - {time_from: '12:40', time_to: '12:50'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}

  items_list_url: https://разборкасокол.рф/
  items_list_selector: .//a
  url_pattern: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/.+/
  url_pattern_detail: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/[^\/]+\/[^\/]+.html$/
  max_depth: 7
  selectors:
      title: //*[@id="content"]/h1
      url: //*[@id="image"]/@src
      price: //div[@class="price"][1]

autoinfo51:
  active: true
  url: http://www.autoinfo51.ru
  class: App\Parser\Spider\DefaultSpider
  work_time:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '22:30'}
    Wednesdays:
      - {time_from: '10:00', time_to: '10:13'}
    Thursdays:
      - {time_from: '12:40', time_to: '12:55'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}

  items_list_url: http://www.autoinfo51.ru
  items_list_selector: .//a
  url_pattern: /^http:\/\/www.autoinfo51.ru\/catalog\/.+/
  url_pattern_detail: /^http:\/\/www.autoinfo51.ru\/catalog\/[\d]+\/[\d]+\/$/
  max_depth: 4
  request_dalay: 500
  selectors:
      row: //table[@class="catalog"]/tr[position() >= 2]
      title: //td[3]
      price: //td[6]
      img: //td[7]/a/@href