# ParsersConfig config
sv-company:
  active: false
  url: https://sv-company.ru/
  class: App\Parser\Spider\Spider
  items_list_url: https://sv-company.ru/avtozapchasti/avtozapchasti-b-u/
  url_pattern: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/.+/
  url_pattern_detail: /https:\/\/sv-company.ru\/avtozapchasti\/avtozapchasti-b-u\/[^\/]+\/$/
  items_list_selector: .//a
  selectors:
      title:
        value: './/h1[@class="product__title"]'
      brand:
        value: './/nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[3]/a'
      model:
        value: './/nav/ul[@class="breadcrumbs page__breadcrumbs"]/li[4]/a'
      img:
        value: './/img[@class="gallery__img"][1]/@src'
        isRelativePath: True
      price:
        value: './/span[@class="product__price"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      isAvalable:
        value: './/tbody/tr[td="Статус"]/td[2]'

razbor-nt:
  active: false
  url: http://razbor-nt.ru/
  class: App\Parser\Spider\Spider
  items_list_url: http://razbor-nt.ru/
  items_list_selector: .//a
  url_pattern: /http:\/\/razbor-nt.ru\/[^\?\/]+\//
  url_pattern_detail: /http:\/\/razbor-nt.ru\/[^\/]+\/[^\/]+\/[^\/]+\/[^\/]+.html$/
  request_dalay: 350
  selectors:
      title:
        value: '//*[@id="content"]/div[@class="b1c-good"]/h1'
      brand:
        value: '//*[@id="content"]/div/div[@class="breadcrumb-style"]/a[2]'
      model:
        value: '//*[@id="content"]/div/div[@class="breadcrumb-style"]/a[3]'
      img:
        value: '//*[@id="image"]/@src'
        isRelativePath: False
      price:
        value: '//div[@class="price"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'

разборкасокол:
  active: false
  url: https://разборкасокол.рф/
  class: App\Parser\Spider\Spider
  items_list_url: https://разборкасокол.рф/
  items_list_selector: .//a
  url_pattern: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai((?!\/shiny\/|\/vw\/).)+\//
  url_pattern_detail: /https:\/\/xn--80aacxqbhucbnep.xn--p1ai\/[^\/]+\/[^\/]+.html$/
  max_depth: 7
  selectors:
      title:
        value: '//*[@id="content"]/h1'
      brand:
        value: '//div[@class="breadcrumb"]/a[2]'
      model:
        value: '//*[@id="content"]/h1'
        need_parse_model_by_brand: true
      description:
        value: '//div[@class="opisanie_tovar"]'
      img:
        value: '//*[@id="image"]/@src'
        isRelativePath: False
      price:
        value: '//div[@class="price"][1]'
        preg_replace:
          pattern: '/\\t+/'
          replace: ' '
        regexp: '/\d\s?\d+(\s?\d+)?/'

autoinfo51:
  active: false
  url: http://www.autoinfo51.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://www.autoinfo51.ru
  items_list_selector: .//a
  url_pattern: /^http:\/\/www.autoinfo51.ru\/catalog\/.+/
  url_pattern_detail: /^http:\/\/www.autoinfo51.ru\/catalog\/[\d]+\/[\d]+\/$/
  max_depth: 4
  request_dalay: 500
  selectors:
      row:
        value: '//table[@class="catalog"]/tr[position() >= 2]'
      brand_model:
        value: '//td[2]'
        need_parse_model_and_brand: true
      title:
        value: '//td[3]'
      description:
        value: '//td[5]'
      price:
        value: '//td[6]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//td[7]/a/@href'
        isRelativePath: False

raz45:
  active: false
  url: http://raz45.ru
  class: App\Parser\Spider\Spider
  items_list_url: http://raz45.ru
  items_list_selector: .//a
  url_pattern: /http:\/\/raz45.ru\/automotiveparts\/[^\?]+$/
  url_pattern_detail: /^http:\/\/raz45.ru\/automotiveparts\/[^\?][0-9]+$/
  max_depth: 4
  request_dalay: 200
  selectors:
      brand_model:
        value: '//h1[@id="page-title"]'
        need_parse_model_and_brand: true
      title:
        value: '//h1[@id="page-title"]'
      price:
        value: '//td[@class="component-total"]'
        regexp: '/\d\s?\d+(\s?\d+)?/'
      img:
        value: '//span[@class="field-item even"][1]/a/img/@src'

avito-razorbor-voroneg:
  active: true
  url: https://www.avito.ru/razorbor-voroneg/rossiya/zapchasti_i_aksessuary?view=list
  class: App\Parser\Spider\Spider
  items_list_url: https://www.avito.ru/razorbor-voroneg/rossiya/zapchasti_i_aksessuary?view=list
  items_list_selector: .//a
  url_pattern: /https:\/\/www.avito.ru\/(razorbor-voroneg\/rossiya\/zapchasti_i_aksessuary\?p=[0-9]{1,2}|voronezh\/zapchasti_i_aksessuary\/.+)/
  url_pattern_detail: /https:\/\/www.avito.ru\/voronezh\/zapchasti_i_aksessuary\/.+/
  max_depth: 10
  request_dalay: 1500
  selectors:
      brand_model:
        value: '//span[@class="title-info-title-text"]'
        need_parse_model_and_brand: true
      title:
        value: '//span[@class="title-info-title-text"]'
      price:
        value: '//*[@id="price-value"]/span'
      img:
        value: '//span[@class="gallery-img-cover"]/img/@src'

