# Shedule config

sv-company:
  Mondays:
  Tuesdays:
    - {time_from: '10:00', time_to: '12:00'}
    - {time_from: '12:00', time_to: '22:00'}
  Wednesdays:
    - {time_from: '10:00', time_to: '18:20'}
  Thursdays:
    - {time_from: '10:00', time_to: '12:40'}
  Fridays:
    - {time_from: '10:00', time_to: '20:00'}
  Saturdays:
   - {time_from: '10:00', time_to: '20:00'}
  Sundays:
    - {time_from: '10:00', time_to: '20:00'}

razbor-nt:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '12:00'}
      - {time_from: '12:00', time_to: '22:00'}
    Wednesdays:
      - {time_from: '10:00', time_to: '20:00'}
    Thursdays:
      - {time_from: '12:38', time_to: '12:45'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}

разборкасокол:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '12:00'}
      - {time_from: '12:00', time_to: '22:00'}
    Wednesdays:
      - {time_from: '10:00', time_to: '20:00'}
    Thursdays:
      - {time_from: '12:40', time_to: '12:50'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}

autoinfo51:
    Mondays:
      - {time_from: '10:00', time_to: '20:00'}
    Tuesdays:
      - {time_from: '10:00', time_to: '22:30'}
    Wednesdays:
      - {time_from: '10:00', time_to: '10:13'}
    Thursdays:
      - {time_from: '12:40', time_to: '12:55'}
    Fridays:
      - {time_from: '10:00', time_to: '20:00'}
    Saturdays:
     - {time_from: '10:00', time_to: '20:00'}
    Sundays:
      - {time_from: '10:00', time_to: '20:00'}